CREATE SEQUENCE PRODUCTO_ID;
CREATE SEQUENCE OPERACION_ID;
CREATE SEQUENCE PUNTO_ATENCION_ID;
CREATE SEQUENCE DIRECCIONES_ID;

CREATE TABLE PERSONA
    (NUMERO_DOCUMENTO NUMBER NOT NULL,
    CONSTRAINT PERSONA_PK PRIMARY KEY (NUMERO_DOCUMENTO));
    
CREATE TABLE CIUDADES
    (CIUDAD VARCHAR2(200) NOT NULL, 
    DEPARTAMENTO VARCHAR2(200) NOT NULL,
    CONSTRAINT CIUDADES_PK PRIMARY KEY (CIUDAD));

CREATE TABLE CODIGOS_POSTALES
    (CODIGO NUMBER NOT NULL,
    CIUDAD VARCHAR2(200) NOT NULL,
    CONSTRAINT CODIGOS_POSTALES_PK PRIMARY KEY (CODIGO));

ALTER TABLE CODIGOS_POSTALES
ADD CONSTRAINT FK_A_CIUDADES
    FOREIGN KEY (CIUDAD)
    REFERENCES CIUDADES(CIUDAD)
    ON DELETE CASCADE
ENABLE;
    
CREATE TABLE DIRECCIONES (
    ID NUMBER NOT NULL, 
    DIRECCION VARCHAR2(200) NOT NULL, 
    CODIGO_POSTAL NUMBER NOT NULL, 
    CONSTRAINT DIRECCIONES_PK PRIMARY KEY (ID));
    
ALTER TABLE DIRECCIONES
ADD CONSTRAINT FK_A_CODIGOS_POSTALES
    FOREIGN KEY (CODIGO_POSTAL) 
    REFERENCES CODIGOS_POSTALES(CODIGO)
    ON DELETE CASCADE
ENABLE;

CREATE TABLE CLIENTE (
    NUMERO_DOCUMENTO NUMBER NOT NULL, 
    TIPO_DOCUMENTO VARCHAR2(200) NOT NULL,
    NOMBRE VARCHAR2(200) NOT NULL, 
    NACIONALIDAD VARCHAR2(200) NOT NULL,
    DIRECCIONES NUMBER NOT NULL,
    DIRECCION_ELECTRONICA VARCHAR2(200) NOT NULL, 
    TELEFONO NUMBER NOT NULL, 
    PALABRA_CLAVE VARCHAR2(200) NOT NULL, 
    TIPO_CLIENTE VARCHAR2(200) NOT NULL, 
    CONSTRAINT CLIENTE_PK PRIMARY KEY (NUMERO_DOCUMENTO)
);

ALTER TABLE CLIENTE
ADD CONSTRAINT FK_A_PERSONA
    FOREIGN KEY (NUMERO_DOCUMENTO)
    REFERENCES PERSONA(NUMERO_DOCUMENTO)
    ON DELETE CASCADE
ADD CONSTRAINT FK_A_DIRECCIONES
    FOREIGN KEY (DIRECCIONES)
    REFERENCES DIRECCIONES(ID)
    ON DELETE CASCADE
ADD CONSTRAINT CK_TIPO_CLIENTE
    CHECK (TIPO_CLIENTE IN ('Natural', 'Juridica'))
ENABLE;

CREATE TABLE OFICINA
    (NOMBRE VARCHAR2(200) NOT NULL,
    DIRECCION NUMBER NOT NULL,
    NUM_PUNTOS_ATENCION NUMBER NOT NULL, 
    CONSTRAINT OFICINA_PK PRIMARY KEY (NOMBRE));
    
ALTER TABLE OFICINA 
    ADD CONSTRAINT FK_A_DIRECCIONES_OFICINA
    FOREIGN KEY (DIRECCION)
    REFERENCES DIRECCIONES(ID)
    ON DELETE CASCADE
ENABLE; 


CREATE TABLE EMPLEADO (
    NUMERO_DOCUMENTO NUMBER NOT NULL, 
    TIPO_DOCUMENTO VARCHAR2(200) NOT NULL,
    NOMBRE VARCHAR2(200) NOT NULL, 
    NACIONALIDAD VARCHAR2(200) NOT NULL,
    DIRECCIONES NUMBER NOT NULL,
    DIRECCION_ELECTRONICA VARCHAR2(200) NOT NULL, 
    TELEFONO NUMBER NOT NULL, 
    PALABRA_CLAVE VARCHAR2(200) NOT NULL,
    OFICINA VARCHAR2(200) NOT NULL,
        SUELDO NUMBER NOT NULL,
    TIPO_EMPLEADO VARCHAR2(200) NOT NULL, 
    CONSTRAINT EMPLEADO_PK PRIMARY KEY (NUMERO_DOCUMENTO));

ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_A_PERSONA_EMP
    FOREIGN KEY (NUMERO_DOCUMENTO)
    REFERENCES PERSONA(NUMERO_DOCUMENTO)
    ON DELETE CASCADE
ADD CONSTRAINT FK_A_DIRECCIONES_EMP
    FOREIGN KEY (DIRECCIONES)
    REFERENCES DIRECCIONES(ID)
    ON DELETE CASCADE
ADD CONSTRAINT CK_TIPO_EMPLEADO
    CHECK (TIPO_EMPLEADO IN ('Cajero', 'Gerente Oficina','Gerente General'))
ENABLE;
    
CREATE TABLE PRODUCTO (
    ID NUMBER NOT NULL, 
    CLIENTE NUMBER NOT NULL, 
    CONSTRAINT PRODUCTO_PK PRIMARY KEY (ID));

ALTER TABLE PRODUCTO 
ADD CONSTRAINT KF_A_CLIENTE_PROD
    FOREIGN KEY (CLIENTE)
    REFERENCES PERSONA(NUMERO_DOCUMENTO)
    ON DELETE CASCADE
ENABLE;

CREATE TABLE PUNTO_DE_ATENCION (
    ID NUMBER NOT NULL,
    TIPO VARCHAR2(200) NOT NULL,
    LOCALIZACION NUMBER,
    OFICINA VARCHAR2(200),
    CONSTRAINT PUNTO_DE_ATENCION_PK PRIMARY KEY (ID)
);

ALTER TABLE PUNTO_DE_ATENCION 
ADD CONSTRAINT CHECK_TIPO 
    CHECK (TIPO IN ('PORTALWEB', 'APPMOVIL', 'PUNTO AUTMATICO', 'ATENCION PERSONALIZADA'))
ADD CONSTRAINT  FK_A_DIRECCIONES_PA
    FOREIGN KEY (LOCALIZACION)
    REFERENCES DIRECCIONES(ID)
    ON DELETE CASCADE
ADD CONSTRAINT FK_A_OFICINA
    FOREIGN KEY (OFICINA)
    REFERENCES OFICINA(NOMBRE)
    ON DELETE CASCADE
ENABLE;


CREATE TABLE PRESTAMO (
    ID NUMBER NOT NULL,
    ESTADO VARCHAR2(200) NOT NULL,
    TIPO VARCHAR2(200) NOT NULL,
    INTERES NUMBER NOT NULL,
    CUOTAS NUMBER NOT NULL,
    VALOR_CUOTA NUMBER NOT NULL,
    MONTO NUMBER NOT NULL,
    DIA_CORTE NUMBER NOT NULL,
    SALDO_PENDIENTE NUMBER NOT NULL,
    CONSTRAINT PRESTAMO_PK PRIMARY KEY (ID) 
);

ALTER TABLE PRESTAMO 
ADD CONSTRAINT FK_A_PRODUCTO_P
    FOREIGN KEY (ID)
    REFERENCES PRODUCTO(ID)
    ON DELETE CASCADE
ADD CONSTRAINT CK_ESTADO 
    CHECK (ESTADO IN ('APROBADO', 'CERRADO','RECHAZADO', 'PAGADO'))
ADD CONSTRAINT CK_TIPO
    CHECK (TIPO IN ('vivienda', 'estudio', 'automóvil', 'libre inversión'))
ENABLE;

CREATE TABLE CUENTAS (
    ID NUMBER NOT NULL,
    ESTADO VARCHAR2(200) NOT NULL,
    TIPO VARCHAR2(200) NOT NULL,
    DINERO NUMBER NOT NULL,
    CONSTRAINT CUENTA_PK PRIMARY KEY (ID)
);

ALTER TABLE CUENTAS 
ADD CONSTRAINT FK_A_PRODUCTO_C
    FOREIGN KEY (ID)
    REFERENCES PRODUCTO(ID)
    ON DELETE CASCADE
ADD CONSTRAINT CK_ESTADO_CUENTA
    CHECK (ESTADO IN ('CERRADA', 'ACTIVADA', 'DESACTIVADA'))  
ENABLE;

CREATE TABLE OPERACION_BANCARIA (
    ID NUMBER NOT NULL,
    HORA TIMESTAMP NOT NULL,
    FECHA DATE NOT NULL,
    ID_ORIGEN NUMBER NOT NULL,
    PUNTO_DE_ATENCION NUMBER NOT NULL,
    VALOR NUMBER,
    TIPO VARCHAR2(200) NOT NULL,
    ID_DESTINO NUMBER NOT NULL,
    CONSTRAINT OPERACION_BANCARIA_PK PRIMARY KEY (ID)
);

ALTER TABLE OPERACION_BANCARIA
ADD CONSTRAINT FK_A_PRODUCTO_1
    FOREIGN KEY (ID_ORIGEN)
    REFERENCES PRODUCTO(ID)
    ON DELETE CASCADE
ADD CONSTRAINT FK_A_PUNTO_ATENCION
    FOREIGN KEY (PUNTO_DE_ATENCION)
    REFERENCES PUNTO_DE_ATENCION(ID)
    ON DELETE CASCADE
ADD CONSTRAINT CK_TIPO_OPERACION
    CHECK (TIPO IN ('CREAR CUENTA', 'CONSIGNAR', 'RETIRAR', 'TRANSFERIR', 'CERRAR CUENTA', 'DESCTIVAR CUENTA', 'SOLICIATAR', 'APROBAR', 'RECHAZAR', 'PAGAR CUOTA', 'PAGAR CUOTA EXTRAORDINARIA', 'CERRAR')) 
ADD CONSTRAINT FK_A_PRODUCTO_2
    FOREIGN KEY (ID_DESTINO)
    REFERENCES PRODUCTO(ID)
    ON DELETE CASCADE  
ENABLE;

INSERT INTO persona (numero_Documento) VALUES(12345)
 
